/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CarHistory {
  export type HistoryEventStruct = {
    carId: BigNumberish;
    eventType: BigNumberish;
    recordedBy: AddressLike;
    timestamp: BigNumberish;
    description: string;
    documentHash: string;
    verified: boolean;
  };

  export type HistoryEventStructOutput = [
    carId: bigint,
    eventType: bigint,
    recordedBy: string,
    timestamp: bigint,
    description: string,
    documentHash: string,
    verified: boolean
  ] & {
    carId: bigint;
    eventType: bigint;
    recordedBy: string;
    timestamp: bigint;
    description: string;
    documentHash: string;
    verified: boolean;
  };
}

export interface CarHistoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "RECORDER_ROLE"
      | "carHistory"
      | "eventCount"
      | "getCarHistory"
      | "getEvent"
      | "getEventCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "recordEvent"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "verifyEvent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EventRecorded"
      | "EventVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECORDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "carHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCarHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordEvent",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvent",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECORDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "carHistory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eventCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCarHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvent",
    data: BytesLike
  ): Result;
}

export namespace EventRecordedEvent {
  export type InputTuple = [
    carId: BigNumberish,
    eventType: BigNumberish,
    recordedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    carId: bigint,
    eventType: bigint,
    recordedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    carId: bigint;
    eventType: bigint;
    recordedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventVerifiedEvent {
  export type InputTuple = [carId: BigNumberish, eventIndex: BigNumberish];
  export type OutputTuple = [carId: bigint, eventIndex: bigint];
  export interface OutputObject {
    carId: bigint;
    eventIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarHistory extends BaseContract {
  connect(runner?: ContractRunner | null): CarHistory;
  waitForDeployment(): Promise<this>;

  interface: CarHistoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RECORDER_ROLE: TypedContractMethod<[], [string], "view">;

  carHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, bigint, string, string, boolean] & {
        carId: bigint;
        eventType: bigint;
        recordedBy: string;
        timestamp: bigint;
        description: string;
        documentHash: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  eventCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getCarHistory: TypedContractMethod<
    [_carId: BigNumberish],
    [CarHistory.HistoryEventStructOutput[]],
    "view"
  >;

  getEvent: TypedContractMethod<
    [_carId: BigNumberish, _eventIndex: BigNumberish],
    [CarHistory.HistoryEventStructOutput],
    "view"
  >;

  getEventCount: TypedContractMethod<[_carId: BigNumberish], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  recordEvent: TypedContractMethod<
    [
      _carId: BigNumberish,
      _eventType: BigNumberish,
      _description: string,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifyEvent: TypedContractMethod<
    [_carId: BigNumberish, _eventIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECORDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "carHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, bigint, string, string, boolean] & {
        carId: bigint;
        eventType: bigint;
        recordedBy: string;
        timestamp: bigint;
        description: string;
        documentHash: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "eventCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCarHistory"
  ): TypedContractMethod<
    [_carId: BigNumberish],
    [CarHistory.HistoryEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [_carId: BigNumberish, _eventIndex: BigNumberish],
    [CarHistory.HistoryEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEventCount"
  ): TypedContractMethod<[_carId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordEvent"
  ): TypedContractMethod<
    [
      _carId: BigNumberish,
      _eventType: BigNumberish,
      _description: string,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyEvent"
  ): TypedContractMethod<
    [_carId: BigNumberish, _eventIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EventRecorded"
  ): TypedContractEvent<
    EventRecordedEvent.InputTuple,
    EventRecordedEvent.OutputTuple,
    EventRecordedEvent.OutputObject
  >;
  getEvent(
    key: "EventVerified"
  ): TypedContractEvent<
    EventVerifiedEvent.InputTuple,
    EventVerifiedEvent.OutputTuple,
    EventVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "EventRecorded(uint256,uint8,address,uint256)": TypedContractEvent<
      EventRecordedEvent.InputTuple,
      EventRecordedEvent.OutputTuple,
      EventRecordedEvent.OutputObject
    >;
    EventRecorded: TypedContractEvent<
      EventRecordedEvent.InputTuple,
      EventRecordedEvent.OutputTuple,
      EventRecordedEvent.OutputObject
    >;

    "EventVerified(uint256,uint256)": TypedContractEvent<
      EventVerifiedEvent.InputTuple,
      EventVerifiedEvent.OutputTuple,
      EventVerifiedEvent.OutputObject
    >;
    EventVerified: TypedContractEvent<
      EventVerifiedEvent.InputTuple,
      EventVerifiedEvent.OutputTuple,
      EventVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
