/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CarRegistry {
  export type CarStruct = {
    carId: BigNumberish;
    vin: string;
    make: string;
    model: string;
    year: BigNumberish;
    manufacturer: AddressLike;
    currentOwner: AddressLike;
    registrationDate: BigNumberish;
    isActive: boolean;
  };

  export type CarStructOutput = [
    carId: bigint,
    vin: string,
    make: string,
    model: string,
    year: bigint,
    manufacturer: string,
    currentOwner: string,
    registrationDate: bigint,
    isActive: boolean
  ] & {
    carId: bigint;
    vin: string;
    make: string;
    model: string;
    year: bigint;
    manufacturer: string;
    currentOwner: string;
    registrationDate: bigint;
    isActive: boolean;
  };

  export type OwnershipRecordStruct = {
    owner: AddressLike;
    transferDate: BigNumberish;
    transferType: string;
  };

  export type OwnershipRecordStructOutput = [
    owner: string,
    transferDate: bigint,
    transferType: string
  ] & { owner: string; transferDate: bigint; transferType: string };
}

export interface CarRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEALER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "INSURANCE_ROLE"
      | "MANUFACTURER_ROLE"
      | "RTO_ROLE"
      | "SERVICE_PROVIDER_ROLE"
      | "cars"
      | "getCar"
      | "getCarByVin"
      | "getOwnershipHistory"
      | "getRoleAdmin"
      | "getUserCars"
      | "grantRole"
      | "hasRole"
      | "ownershipHistory"
      | "registerCar"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "transferOwnership"
      | "userCars"
      | "vinToCar"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CarDeactivated"
      | "CarRegistered"
      | "OwnershipTransferred"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEALER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSURANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANUFACTURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RTO_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SERVICE_PROVIDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cars", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getCarByVin", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getOwnershipHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCars",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownershipHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCar",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userCars",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vinToCar", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "DEALER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSURANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANUFACTURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RTO_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SERVICE_PROVIDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCarByVin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnershipHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownershipHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userCars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vinToCar", data: BytesLike): Result;
}

export namespace CarDeactivatedEvent {
  export type InputTuple = [carId: BigNumberish];
  export type OutputTuple = [carId: bigint];
  export interface OutputObject {
    carId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarRegisteredEvent {
  export type InputTuple = [
    carId: BigNumberish,
    vin: string,
    manufacturer: AddressLike
  ];
  export type OutputTuple = [carId: bigint, vin: string, manufacturer: string];
  export interface OutputObject {
    carId: bigint;
    vin: string;
    manufacturer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    carId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    transferType: string
  ];
  export type OutputTuple = [
    carId: bigint,
    from: string,
    to: string,
    transferType: string
  ];
  export interface OutputObject {
    carId: bigint;
    from: string;
    to: string;
    transferType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CarRegistry;
  waitForDeployment(): Promise<this>;

  interface: CarRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEALER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INSURANCE_ROLE: TypedContractMethod<[], [string], "view">;

  MANUFACTURER_ROLE: TypedContractMethod<[], [string], "view">;

  RTO_ROLE: TypedContractMethod<[], [string], "view">;

  SERVICE_PROVIDER_ROLE: TypedContractMethod<[], [string], "view">;

  cars: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        carId: bigint;
        vin: string;
        make: string;
        model: string;
        year: bigint;
        manufacturer: string;
        currentOwner: string;
        registrationDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getCar: TypedContractMethod<
    [_carId: BigNumberish],
    [CarRegistry.CarStructOutput],
    "view"
  >;

  getCarByVin: TypedContractMethod<[_vin: string], [bigint], "view">;

  getOwnershipHistory: TypedContractMethod<
    [_carId: BigNumberish],
    [CarRegistry.OwnershipRecordStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserCars: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  ownershipHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string] & {
        owner: string;
        transferDate: bigint;
        transferType: string;
      }
    ],
    "view"
  >;

  registerCar: TypedContractMethod<
    [_vin: string, _make: string, _model: string, _year: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [_carId: BigNumberish, _newOwner: AddressLike, _transferType: string],
    [void],
    "nonpayable"
  >;

  userCars: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  vinToCar: TypedContractMethod<[arg0: string], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEALER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSURANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANUFACTURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RTO_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SERVICE_PROVIDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cars"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        carId: bigint;
        vin: string;
        make: string;
        model: string;
        year: bigint;
        manufacturer: string;
        currentOwner: string;
        registrationDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCar"
  ): TypedContractMethod<
    [_carId: BigNumberish],
    [CarRegistry.CarStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCarByVin"
  ): TypedContractMethod<[_vin: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOwnershipHistory"
  ): TypedContractMethod<
    [_carId: BigNumberish],
    [CarRegistry.OwnershipRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserCars"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownershipHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string] & {
        owner: string;
        transferDate: bigint;
        transferType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCar"
  ): TypedContractMethod<
    [_vin: string, _make: string, _model: string, _year: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [_carId: BigNumberish, _newOwner: AddressLike, _transferType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userCars"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "vinToCar"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;

  getEvent(
    key: "CarDeactivated"
  ): TypedContractEvent<
    CarDeactivatedEvent.InputTuple,
    CarDeactivatedEvent.OutputTuple,
    CarDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "CarRegistered"
  ): TypedContractEvent<
    CarRegisteredEvent.InputTuple,
    CarRegisteredEvent.OutputTuple,
    CarRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "CarDeactivated(uint256)": TypedContractEvent<
      CarDeactivatedEvent.InputTuple,
      CarDeactivatedEvent.OutputTuple,
      CarDeactivatedEvent.OutputObject
    >;
    CarDeactivated: TypedContractEvent<
      CarDeactivatedEvent.InputTuple,
      CarDeactivatedEvent.OutputTuple,
      CarDeactivatedEvent.OutputObject
    >;

    "CarRegistered(uint256,string,address)": TypedContractEvent<
      CarRegisteredEvent.InputTuple,
      CarRegisteredEvent.OutputTuple,
      CarRegisteredEvent.OutputObject
    >;
    CarRegistered: TypedContractEvent<
      CarRegisteredEvent.InputTuple,
      CarRegisteredEvent.OutputTuple,
      CarRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(uint256,address,address,string)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
