/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CarHistory__factory } from "./CarHistory__factory";
export { CarRegistry__factory } from "./CarRegistry__factory";
